### ISSUE TITLE
How to get started ?

### ISSUE THREAD

**Issue by hemantbaxi** [finos/glue#111]
## Support Question

I am interested to learn about glue and also contribute.

Looking at the README or other available documentation, it is not clear how to deploy it ?

It is also not clear what other tools can you integrate this with or how to use it ?

Can you please give some pointers to get started ?

Thanks,
 -- Hemant

**Comment by hemantbaxi** [comment]
Thanks Ana !! This is helpful.

So, what type of contribution are you looking for in the project ?

Thanks,
    -- Hemant

**Comment by AnaAntonova** [comment]
Any type of contribution is welcome. It can be either suggesting optimization of the model, adding new domains, or clarifying definitions that are covered by the model.
Best,
Ana
