### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by maoo** [finos/glue#112]
Hi @AnaAntonova !

I see that there haven't been updates on this repo since a long time; is it still used/relevant, or shall we archive it?

Thanks in advance!

**Comment by TheJuanAndOnly99** [comment]
Hi @yasenfingarov, 

Can this repository be archived?

**Comment by yasenfingarov** [comment]
Let me check internally, I am assigned to a different project

On 14 Apr 2023, at 14:47, Juan Estrella ***@***.***> wrote:



Hi @yasenfingarov<https://urldefense.com/v3/__https://github.com/yasenfingarov__;!!GF_29dbcQIUBPA!z1x8J14WEa-n9FYil1FE68Q5da1upSifylQrHkovkRyy5RKi5bo9S7M1_O4fiE3ySWpbgFixVGY9XQQp5SU-nLrNhf97$>,

Can this repository be archived?

**Comment by maoo** [comment]
Hi @yasenfingarov - do you have any update on this? Thanks!

**Comment by finos-admin** [comment]
Archiving repository.
